-- create schema infybank; 
use infybank;
CREATE TABLE `account_config` (
  `ACCT_TYPE` char(1) NOT NULL,
  `INTEREST_RATE` decimal(12,4) NOT NULL,
  `LST_UPDT_ID` varchar(10) NOT NULL,
  `LST_UPDT_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MIN_BALANCE` decimal(12,4) NOT NULL,
  PRIMARY KEY (`ACCT_TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `account_transaction` (
  `TXN_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ACCT_NO` varchar(20) NOT NULL,
  `CLOSING_BAL` decimal(12,4) NOT NULL,
  `CUST_ID` int(11) NOT NULL,
  `LST_UPDT_ID` varchar(10) NOT NULL,
  `LST_UPDT_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `OPENING_BAL` decimal(12,4) NOT NULL,
  `REF_ID` varchar(20) DEFAULT NULL,
  `REMARKS` varchar(100) DEFAULT NULL,
  `TXN_AMOUNT` decimal(12,4) NOT NULL,
  `TXN_CATEGORY` char(1) NOT NULL,
  `TXN_DATE` date NOT NULL,
  `TXN_TYP` char(1) NOT NULL,
  PRIMARY KEY (`TXN_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `bank_account` (
  `ACCT_NO` varchar(20) NOT NULL,
  `CUST_ID` int(11) NOT NULL,
  `ACCT_TYPE` char(1) NOT NULL,
  `BALANCE` decimal(12,4) NOT NULL,
  `LST_UPDT_ID` varchar(10) NOT NULL,
  `LST_UPDT_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `SALARIED` char(1) NOT NULL,
  PRIMARY KEY (`ACCT_NO`,`CUST_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `customer` (
  `CUST_ID` int(11) NOT NULL AUTO_INCREMENT,
  `AADHAR_ID` varchar(12) NOT NULL,
  `ADDRESS` varchar(100) NOT NULL,
  `AMOUNT_PREF` varchar(10) NOT NULL DEFAULT 'l',
  `CITY` varchar(30) NOT NULL,
  `CR_DB_NOTIF_LIMIT` decimal(12,4) NOT NULL,
  `DATE_PREF` varchar(15) NOT NULL DEFAULT 'dd/mm/yy',
  `DOB` date NOT NULL,
  `EMAIL_ID` varchar(100) NOT NULL,
  `FIRST_NAME` varchar(50) NOT NULL,
  `LAST_NAME` varchar(50) NOT NULL,
  `LST_UPDT_ID` varchar(10) NOT NULL,
  `LST_UPDT_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `PAN_NO` varchar(10) NOT NULL,
  `PINCODE` varchar(6) NOT NULL,
  `STATE` varchar(30) NOT NULL,
  PRIMARY KEY (`CUST_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `login` (
  `CUST_ID` int(11) NOT NULL,
  `LST_UPDT_ID` varchar(10) NOT NULL,
  `LST_UPDT_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `PASSWORD` varchar(255) NOT NULL,
  `ROLE` char(1) NOT NULL,
  `USER_ID` varchar(10) NOT NULL,
  PRIMARY KEY (`CUST_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;


INSERT INTO `account_config` (`ACCT_TYPE`, `INTEREST_RATE`, `LST_UPDT_ID`, `LST_UPDT_TS`, `MIN_BALANCE`) VALUES ('C', '8', 'SYSTEM', '2016-12-28', '1000.00');
USE sample;
CREATE TABLE BOOKS(
	BOOK_ID int(11) NOT NULL,
	BOOK_NAME varchar(255) NOT NULL,
	PRIMARY KEY ( BOOK_ID )
);

INSERT INTO BOOKS VALUES(1,'HTML 5');
INSERT INTO BOOKS VALUES(2,'CSS 3');
INSERT INTO BOOKS VALUES(3,'Java Script');
INSERT INTO BOOKS VALUES(4,'Angular 5');

SELECT * FROM BOOKS;
