interacts(gatifloxacin,zolpidem,attempted_suicide).
interacts(gatifloxacin,zolpidem,insomnia).
interacts(gatifloxacin,warfarin,cardiac_decompensation).
interacts(gatifloxacin,isosorbide-5-mononitrate,arteriosclerotic_heart_disease).
interacts(gatifloxacin,rosiglitazone,hyperglycaemia).
interacts(gatifloxacin,bortezomib,hyperglycaemia).
interacts(gatifloxacin,mometasone,asthma).
interacts(gatifloxacin,cisplatin,hyperglycaemia).
interacts(gatifloxacin,cisplatin,bone_marrow_failure).
interacts(gatifloxacin,montelukast,difficulty_breathing).
interacts(temazepam,thalidomide,neutropenia).
interacts(temazepam,thalidomide,thrombocytopenia).
interacts(temazepam,timolol,drowsiness).
interacts(temazepam,tizanidine,acid_reflux).
interacts(temazepam,tizanidine,heart_attack).
interacts(temazepam,tolterodine,amnesia).
interacts(temazepam,tolterodine,heart_attack).
interacts(temazepam,tolterodine,loss_of_consciousness).
interacts(temazepam,topiramate,convulsion).
interacts(temazepam,trazodone,arrhythmia).
interacts(temazepam,trazodone,bronchitis).
interacts(temazepam,trazodone,arteriosclerotic_heart_disease).
interacts(temazepam,trazodone,diabetes).
interacts(temazepam,trazodone,hyperlipaemia).
interacts(temazepam,trazodone,heart_attack).
interacts(temazepam,trazodone,osteoarthritis).
interacts(temazepam,trazodone,apoplexy).
interacts(temazepam,trazodone,road_traffic_accident).
interacts(temazepam,triamcinolone,cough).
interacts(temazepam,triamcinolone,insomnia).
interacts(temazepam,trimethoprim,feeling_unwell).
interacts(temazepam,valacyclovir,amnesia).
interacts(temazepam,valacyclovir,road_traffic_accident).
interacts(temazepam,vancomycin,insomnia).
interacts(temazepam,venlafaxine,diabetes).
interacts(temazepam,zolpidem,heart_attack).
interacts(temazepam,zopiclone,amnesia).
interacts(temazepam,zopiclone,anxiety).
interacts(temazepam,zopiclone,drowsiness).
interacts(temazepam,vincristine,insomnia).
interacts(temazepam,warfarin,kidney_failure).
interacts(temazepam,warfarin,aseptic_necrosis_bone).
interacts(temazepam,isosorbide-5-mononitrate,chest_pain).
interacts(temazepam,isosorbide-5-mononitrate,hyperglycaemia).
interacts(temazepam,lithium,diabetes).
interacts(temazepam,lithium,weight_gain).
interacts(temazepam,oxcarbazepine,insomnia).
interacts(temazepam,carboplatin,aseptic_necrosis_bone).
interacts(temazepam,octreotide,drowsiness).
interacts(temazepam,simvastatin,transient_ischaemic_attack).
interacts(temazepam,simvastatin,cardiac_disease).
interacts(temazepam,simvastatin,aching_muscles).
interacts(temazepam,levetiracetam,hallucination).
interacts(temazepam,tamsulosin,arteriosclerotic_heart_disease).
interacts(temazepam,tamsulosin,arterial_pressure_nos_decreased).
interacts(temazepam,perindopril,arterial_pressure_nos_decreased).
interacts(temazepam,aripiprazole,drowsiness).
interacts(temazepam,aripiprazole,tardive_dyskinesia).
interacts(temazepam,aripiprazole,insomnia).
interacts(temazepam,tiotropium,cough).
interacts(temazepam,tiotropium,dysphonia).
interacts(temazepam,duloxetine,drowsiness).
interacts(temazepam,duloxetine,tremor).
interacts(temazepam,ziprasidone,acute_brain_syndrome).
interacts(temazepam,ziprasidone,insomnia).
interacts(temazepam,olopatadine,chest_pain).
interacts(temazepam,fluticasone,cough).
interacts(temazepam,fluticasone,insomnia).
interacts(temazepam,zoledronic_acid,neumonia).
interacts(temazepam,rosiglitazone,anorexia).
interacts(temazepam,rosiglitazone,hyperglycaemia).
interacts(temazepam,rosiglitazone,hypoglycaemia).
interacts(temazepam,rosiglitazone,nausea).
interacts(temazepam,allopurinol,arterial_pressure_nos_decreased).
interacts(temazepam,lactulose,hypoventilation).
interacts(temazepam,bortezomib,bone_marrow_failure).
interacts(temazepam,bortezomib,deep_vein_thromboses).
interacts(temazepam,valdecoxib,hyperlipaemia).
interacts(temazepam,valdecoxib,arthropathy).
interacts(temazepam,valdecoxib,heart_attack).
interacts(temazepam,desloratadine,insomnia).
interacts(temazepam,varenicline,anxiety).
interacts(temazepam,varenicline,drowsiness).
interacts(temazepam,varenicline,difficulty_breathing).
interacts(temazepam,varenicline,insomnia).
interacts(temazepam,sorafenib,insomnia).
interacts(temazepam,lenalidomide,aseptic_necrosis_bone).
interacts(temazepam,nystatin,insomnia).
interacts(temazepam,rosuvastatin,chest_pain).
interacts(temazepam,montelukast,cough).
interacts(temazepam,tegaserod,insomnia).
interacts(temazepam,sucralfate,insomnia).
interacts(temozolomide,thalidomide,neutropenia).
interacts(temozolomide,vancomycin,bone_marrow_failure).
interacts(temozolomide,venlafaxine,insomnia).
interacts(temozolomide,zolpidem,constipated).
interacts(temozolomide,oxcarbazepine,neutropenia).
interacts(temozolomide,carboplatin,dehydration).
interacts(temozolomide,lactulose,dehydration).
interacts(temozolomide,cisplatin,anaemia).
interacts(temozolomide,cisplatin,neumonia).
interacts(terazosin,tramadol,drug_withdrawal).
interacts(terazosin,zolpidem,insomnia).
interacts(terazosin,carboplatin,neumonia).
interacts(terazosin,carboplatin,thrombocytopenia).
interacts(terazosin,simvastatin,apoplexy).
interacts(terazosin,simvastatin,aching_muscles).
interacts(terazosin,fluticasone,asthma).
interacts(terazosin,fluticasone,difficulty_breathing).
interacts(terazosin,fluticasone,wheeze).
interacts(terazosin,allopurinol,kidney_failure).
interacts(terazosin,allopurinol,bradycardia).
interacts(terazosin,valdecoxib,cardiac_disease).
interacts(terazosin,ezetimibe,aching_muscles).
interacts(terazosin,dutasteride,aseptic_necrosis_bone).
interacts(terazosin,montelukast,asthma).
interacts(terazosin,montelukast,difficulty_breathing).
interacts(terazosin,montelukast,wheeze).
interacts(terbinafine,tramadol,muscle_spasm).
interacts(terbinafine,triazolam,amnesia).
interacts(terbinafine,warfarin,arterial_pressure_nos_decreased).
interacts(terbinafine,warfarin,bradycardia).
interacts(terbinafine,rosiglitazone,hyperglycaemia).
interacts(terbinafine,allopurinol,arterial_pressure_nos_decreased).
interacts(testosterone,topiramate,convulsion).
interacts(testosterone,triamcinolone,cough).
interacts(testosterone,valsartan,arterial_pressure_nos_increased).
interacts(testosterone,venlafaxine,insomnia).
interacts(testosterone,zolpidem,chest_pain).
interacts(testosterone,zolpidem,heart_attack).
interacts(testosterone,tiotropium,difficulty_breathing).
interacts(testosterone,duloxetine,diabetes).
interacts(testosterone,fluticasone,wheeze).
interacts(testosterone,telmisartan,high_blood_pressure).
interacts(testosterone,zoledronic_acid,neutropenia).
interacts(testosterone,rosiglitazone,ecchymoses).
interacts(testosterone,rosiglitazone,hyperglycaemia).
interacts(testosterone,rosiglitazone,hypoglycaemia).
interacts(testosterone,rosiglitazone,nausea).
interacts(testosterone,rosiglitazone,loss_of_weight).
interacts(testosterone,tadalafil,scotoma).
interacts(testosterone,atazanavir,acidosis).
interacts(testosterone,ezetimibe,extremity_pain).
interacts(testosterone,dutasteride,facial_flushing).
interacts(testosterone,rosuvastatin,chest_pain).
interacts(testosterone,rosuvastatin,arteriosclerotic_heart_disease).
interacts(testosterone,montelukast,cough).
interacts(testosterone,tenofovir_disoproxil_fumarate,adenopathy).
interacts(tetracycline,zolpidem,drowsiness).
interacts(thalidomide,tolterodine,thrombocytopenia).
interacts(thalidomide,triamcinolone,neumonia).
interacts(thalidomide,venlafaxine,hypoventilation).
interacts(thalidomide,zolpidem,insomnia).
interacts(thalidomide,vincristine,neutropenia).
interacts(thalidomide,megestrol,dehydration).
interacts(thalidomide,megestrol,infection).
interacts(thalidomide,megestrol,multiple_myeloma).
interacts(thalidomide,megestrol,neutropenia).
interacts(thalidomide,carboplatin,anaemia).
interacts(thalidomide,carboplatin,aseptic_necrosis_bone).
interacts(thalidomide,simvastatin,apoplexy).
interacts(thalidomide,fluticasone,asthma).
interacts(thalidomide,rosiglitazone,anorexia).
interacts(thalidomide,lactulose,aseptic_necrosis_bone).
interacts(thalidomide,bortezomib,infection).
interacts(thalidomide,bortezomib,myelodysplasia).
interacts(thalidomide,nystatin,aseptic_necrosis_bone).
interacts(thalidomide,cisplatin,leucopenia).
interacts(thalidomide,montelukast,difficulty_breathing).
interacts(thalidomide,montelukast,thrombocytopenia).
interacts(thalidomide,sucralfate,neumonia).
interacts(thiotepa,carboplatin,aseptic_necrosis_bone).
interacts(thiothixene,lithium,pancreatitis).
interacts(thiothixene,aripiprazole,ketoacidosis).
interacts(tiagabine,venlafaxine,diabetes).
interacts(tiagabine,oxcarbazepine,diabetes).
interacts(tiagabine,duloxetine,diabetes).
interacts(ticlopidine,valsartan,heart_attack).
interacts(ticlopidine,warfarin,cardiac_decompensation).
interacts(timolol,tolterodine,heart_attack).
interacts(timolol,zolpidem,anxiety).
interacts(timolol,zolpidem,agitated).
interacts(timolol,simvastatin,transient_ischaemic_attack).
interacts(timolol,simvastatin,arteriosclerotic_heart_disease).
interacts(timolol,simvastatin,apoplexy).
interacts(timolol,brinzolamide,cataract).
interacts(timolol,rosiglitazone,hypoglycaemia).
interacts(timolol,allopurinol,cardiac_failure).
interacts(timolol,allopurinol,high_blood_pressure).
interacts(timolol,ezetimibe,heart_attack).
interacts(timolol,rosuvastatin,heart_attack).
interacts(timolol,travoprost,conjunctivitis).
interacts(timolol,travoprost,glaucoma).
interacts(timolol,bimatoprost,conjunctivitis).
interacts(timolol,bimatoprost,cataract).
interacts(timolol,bimatoprost,blurred_vision).
interacts(tirofiban,simvastatin,apoplexy).
interacts(tizanidine,tolterodine,chest_pain).
interacts(tizanidine,tolterodine,elevated_cholesterol).
interacts(tizanidine,tolterodine,osteoarthritis).
interacts(tizanidine,tolterodine,pain).
interacts(tizanidine,tolterodine,apoplexy).
interacts(tizanidine,topiramate,anxiety).
interacts(tizanidine,topiramate,apoplexy).
interacts(tizanidine,tramadol,aseptic_necrosis_bone).
interacts(tizanidine,tramadol,abnormal_gait).
interacts(tizanidine,trazodone,arrhythmia).
interacts(tizanidine,trazodone,transient_ischaemic_attack).
interacts(tizanidine,trazodone,cardiac_disease).
interacts(tizanidine,trazodone,hyperlipaemia).
interacts(tizanidine,trazodone,chronic_obstructive_airway_disease).
interacts(tizanidine,trazodone,heart_attack).
interacts(tizanidine,trazodone,osteoarthritis).
interacts(tizanidine,triamcinolone,hyperhidrosis).
interacts(tizanidine,triamcinolone,apoplexy).
interacts(tizanidine,valsartan,muscle_spasm).
interacts(tizanidine,venlafaxine,convulsion).
interacts(tizanidine,zolmitriptan,high_blood_pressure).
interacts(tizanidine,zolpidem,attempted_suicide).
interacts(tizanidine,zolpidem,tremor).
interacts(tizanidine,zolpidem,agitated).
interacts(tizanidine,zonisamide,apoplexy).
interacts(tizanidine,zopiclone,chest_pain).
interacts(tizanidine,zopiclone,acid_reflux).
interacts(tizanidine,warfarin,difficulty_breathing).
interacts(tizanidine,oxcarbazepine,apoplexy).
interacts(tizanidine,tamsulosin,arteriosclerotic_heart_disease).
interacts(tizanidine,tamsulosin,hypoventilation).
interacts(tizanidine,duloxetine,drowsiness).
interacts(tizanidine,duloxetine,hypoventilation).
interacts(tizanidine,fluticasone,pleural_pain).
interacts(tizanidine,fluticasone,cough).
interacts(tizanidine,fluticasone,difficulty_breathing).
interacts(tizanidine,fluticasone,chronic_obstructive_airway_disease).
interacts(tizanidine,rosiglitazone,hyperglycaemia).
interacts(tizanidine,allopurinol,neumonia).
interacts(tizanidine,allopurinol,apoplexy).
interacts(tizanidine,lactulose,chest_pain).
interacts(tizanidine,lactulose,pain).
interacts(tizanidine,valdecoxib,arteriosclerotic_heart_disease).
interacts(tizanidine,valdecoxib,cardiac_disease).
interacts(tizanidine,valdecoxib,apoplexy).
interacts(tizanidine,desloratadine,drowsiness).
interacts(tizanidine,desloratadine,hypoventilation).
interacts(tizanidine,ezetimibe,elevated_cholesterol).
interacts(tizanidine,ezetimibe,pain).
interacts(tizanidine,ezetimibe,muscle_spasm).
interacts(tizanidine,ezetimibe,aching_muscles).
interacts(tizanidine,varenicline,difficulty_breathing).
interacts(tizanidine,varenicline,drug_addiction).
interacts(tizanidine,glatiramer_acetate,heart_attack).
interacts(tizanidine,glatiramer_acetate,pain).
interacts(tizanidine,nystatin,pleural_pain).
interacts(tizanidine,nystatin,heart_attack).
interacts(tizanidine,nystatin,nausea).
interacts(tizanidine,tegaserod,heart_attack).
interacts(tobramycin,zolpidem,anxiety).
interacts(tobramycin,fluticasone,asthma).
interacts(tobramycin,nitric_oxide,body_temperature_increased).
interacts(tobramycin,nystatin,anaemia).
interacts(tolterodine,tramadol,pain).
interacts(tolterodine,tramadol,muscle_spasm).
interacts(tolterodine,trazodone,apoplexy).
interacts(tolterodine,triamcinolone,wheeze).
interacts(tolterodine,venlafaxine,attempted_suicide).
interacts(tolterodine,venlafaxine,blurred_vision).
interacts(tolterodine,venlafaxine,insomnia).
interacts(tolterodine,zolpidem,heart_attack).
interacts(tolterodine,zolpidem,drug_addiction).
interacts(tolterodine,warfarin,cardiac_failure).
interacts(tolterodine,medroxyprogesterone,breakthrough_bleeding).
interacts(tolterodine,simvastatin,arteriosclerotic_heart_disease).
interacts(tolterodine,simvastatin,high_blood_pressure).
interacts(tolterodine,simvastatin,heart_attack).
interacts(tolterodine,duloxetine,confusion).
interacts(tolterodine,duloxetine,agitated).
interacts(tolterodine,fluticasone,cough).
interacts(tolterodine,fluticasone,dysphonia).
interacts(tolterodine,rosiglitazone,hypoglycaemia).
interacts(tolterodine,rosiglitazone,loss_of_weight).
interacts(tolterodine,valdecoxib,apoplexy).
interacts(tolterodine,pregabalin,apoplexy).
interacts(tolterodine,ezetimibe,muscle_spasm).
interacts(tolterodine,rosuvastatin,heart_attack).
interacts(tolterodine,tegaserod,heart_attack).
interacts(tolterodine,sucralfate,apoplexy).
interacts(topiramate,tramadol,eruption).
interacts(topiramate,tramadol,migraine).
interacts(topiramate,trazodone,arrhythmia).
interacts(topiramate,trazodone,transient_ischaemic_attack).
interacts(topiramate,trazodone,chest_pain).
interacts(topiramate,trazodone,elevated_cholesterol).
interacts(topiramate,trazodone,osteoarthritis).
interacts(topiramate,trazodone,apoplexy).
interacts(topiramate,triamcinolone,difficulty_breathing).
interacts(topiramate,valacyclovir,convulsion).
interacts(topiramate,venlafaxine,eruption).
interacts(topiramate,venlafaxine,convulsion).
interacts(topiramate,venlafaxine,tremor).
interacts(topiramate,zolpidem,hallucination).
interacts(topiramate,zonisamide,eruption).
interacts(topiramate,zonisamide,status_epilepticus).
interacts(topiramate,warfarin,anaemia).
interacts(topiramate,isosorbide-5-mononitrate,arteriosclerotic_heart_disease).
interacts(topiramate,lithium,diabetes).
interacts(topiramate,lithium,mod).
interacts(topiramate,lithium,diabetic_acidosis).
interacts(topiramate,oxcarbazepine,eruption).
interacts(topiramate,simvastatin,arteriosclerotic_heart_disease).
interacts(topiramate,simvastatin,elevated_cholesterol).
interacts(topiramate,aripiprazole,pancreatitis).
interacts(topiramate,tiotropium,asthma).
interacts(topiramate,duloxetine,diabetes).
interacts(topiramate,duloxetine,attempted_suicide).
interacts(topiramate,ziprasidone,convulsion).
interacts(topiramate,fluticasone,difficulty_breathing).
interacts(topiramate,rosiglitazone,eruption).
interacts(topiramate,rosiglitazone,hypoglycaemia).
interacts(topiramate,rosiglitazone,convulsion).
interacts(topiramate,allopurinol,eruption).
interacts(topiramate,lactulose,migraine).
interacts(topiramate,9-hydroxyrisperidone,eruption).
interacts(topiramate,valdecoxib,heart_attack).
interacts(topiramate,almotriptan,eruption).
interacts(topiramate,desloratadine,asthma).
interacts(topiramate,pregabalin,eruption).
interacts(topiramate,olmesartan_medoxomil,feeling_unwell).
interacts(topiramate,varenicline,epilepsy).
interacts(topiramate,montelukast,cough).
interacts(topiramate,montelukast,difficulty_breathing).
interacts(topiramate,montelukast,convulsion).
interacts(tramadol,trazodone,cardiac_disease).
interacts(tramadol,trazodone,cardiac_failure).
interacts(tramadol,trazodone,heart_attack).
interacts(tramadol,trazodone,apoplexy).
interacts(tramadol,trazodone,phlebothrombosis).
interacts(tramadol,triamcinolone,asthma).
interacts(tramadol,triamcinolone,difficulty_breathing).
interacts(tramadol,triamcinolone,cardiac_disease).
interacts(tramadol,valsartan,arterial_pressure_nos_increased).
interacts(tramadol,venlafaxine,diabetes).
interacts(tramadol,zolpidem,attempted_suicide).
interacts(tramadol,zopiclone,pain).
interacts(tramadol,warfarin,pain).
interacts(tramadol,megestrol,pain).
interacts(tramadol,megestrol,hypoventilation).
interacts(tramadol,isosorbide-5-mononitrate,apoplexy).
interacts(tramadol,lithium,drowsiness).
interacts(tramadol,oxcarbazepine,anxiety).
interacts(tramadol,carboplatin,pain).
interacts(tramadol,simvastatin,cardiac_disease).
interacts(tramadol,simvastatin,acute_kidney_failure).
interacts(tramadol,simvastatin,aching_muscles).
interacts(tramadol,clarithromycin,neumonia).
interacts(tramadol,levetiracetam,drowsiness).
interacts(tramadol,levetiracetam,drug_withdrawal).
interacts(tramadol,aripiprazole,diabetes).
interacts(tramadol,tiotropium,asthma).
interacts(tramadol,tiotropium,bronchitis).
interacts(tramadol,tiotropium,hypoventilation).
interacts(tramadol,duloxetine,diabetes).
interacts(tramadol,duloxetine,drowsiness).
interacts(tramadol,duloxetine,hypoventilation).
interacts(tramadol,duloxetine,insomnia).
interacts(tramadol,ibandronate,constipated).
interacts(tramadol,olopatadine,hypoventilation).
interacts(tramadol,fluticasone,anxiety).
interacts(tramadol,fluticasone,cough).
interacts(tramadol,fluticasone,elevated_cholesterol).
interacts(tramadol,rosiglitazone,anxiety).
interacts(tramadol,rosiglitazone,acid_reflux).
interacts(tramadol,rosiglitazone,hypoglycaemia).
interacts(tramadol,rosiglitazone,pain).
interacts(tramadol,rosiglitazone,loss_of_weight).
interacts(tramadol,rosiglitazone,hypoventilation).
interacts(tramadol,lactulose,back_ache).
interacts(tramadol,lactulose,heart_attack).
interacts(tramadol,lactulose,abnormal_gait).
interacts(tramadol,valdecoxib,transient_ischaemic_attack).
interacts(tramadol,valdecoxib,cardiac_disease).
interacts(tramadol,desloratadine,difficulty_breathing).
interacts(tramadol,pregabalin,anxiety).
interacts(tramadol,olmesartan_medoxomil,fainting).
interacts(tramadol,ezetimibe,elevated_cholesterol).
interacts(tramadol,ezetimibe,muscle_disorder).
interacts(tramadol,varenicline,back_ache).
interacts(tramadol,rosuvastatin,hypoventilation).
interacts(tramadol,montelukast,anxiety).
interacts(tramadol,montelukast,asthma).
interacts(tramadol,montelukast,difficulty_breathing).
interacts(tramadol,montelukast,hypoventilation).
interacts(trazodone,triamcinolone,phlebothrombosis).
interacts(trazodone,valsartan,chest_pain).
interacts(trazodone,valsartan,acid_reflux).
interacts(trazodone,valsartan,cardiac_disease).
interacts(trazodone,valsartan,hyperlipaemia).
interacts(trazodone,valsartan,heart_attack).
interacts(trazodone,valsartan,pain).
interacts(trazodone,valsartan,kidney_failure).
interacts(trazodone,valsartan,sleep_apnea).
interacts(trazodone,venlafaxine,cardiac_disease).
interacts(trazodone,venlafaxine,hyperlipaemia).
interacts(trazodone,venlafaxine,heart_attack).
interacts(trazodone,venlafaxine,osteoarthritis).
interacts(trazodone,venlafaxine,apoplexy).
interacts(trazodone,zaleplon,apoplexy).
interacts(trazodone,zolpidem,cardiac_disease).
interacts(trazodone,zolpidem,heart_attack).
interacts(trazodone,zolpidem,phlebothrombosis).
interacts(trazodone,warfarin,transient_ischaemic_attack).
interacts(trazodone,warfarin,heart_attack).
interacts(trazodone,warfarin,apoplexy).
interacts(trazodone,medroxyprogesterone,heart_attack).
interacts(trazodone,isosorbide-5-mononitrate,arrhythmia).
interacts(trazodone,simvastatin,arrhythmia).
interacts(trazodone,simvastatin,disorder_renal).
interacts(trazodone,simvastatin,embolism_pulmonary).
interacts(trazodone,simvastatin,phlebothrombosis).
interacts(trazodone,aripiprazole,chest_pain).
interacts(trazodone,aripiprazole,elevated_cholesterol).
interacts(trazodone,duloxetine,cardiac_disease).
interacts(trazodone,duloxetine,elevated_cholesterol).
interacts(trazodone,duloxetine,heart_attack).
interacts(trazodone,ziprasidone,chest_pain).
interacts(trazodone,ziprasidone,elevated_cholesterol).
interacts(trazodone,ziprasidone,still_birth).
interacts(trazodone,fluticasone,angina).
interacts(trazodone,fluticasone,anxiety).
interacts(trazodone,fluticasone,arrhythmia).
interacts(trazodone,fluticasone,chronic_obstructive_airway_disease).
interacts(trazodone,rosiglitazone,chest_pain).
interacts(trazodone,rosiglitazone,acid_reflux).
interacts(trazodone,rosiglitazone,elevated_cholesterol).
interacts(trazodone,rosiglitazone,heart_attack).
interacts(trazodone,rosiglitazone,apoplexy).
interacts(trazodone,rosiglitazone,phlebothrombosis).
interacts(trazodone,allopurinol,cardiac_disease).
interacts(trazodone,allopurinol,apoplexy).
interacts(trazodone,valdecoxib,arrhythmia).
interacts(trazodone,valdecoxib,transient_ischaemic_attack).
interacts(trazodone,valdecoxib,hyperlipaemia).
interacts(trazodone,valdecoxib,heart_attack).
interacts(trazodone,valdecoxib,phlebothrombosis).
interacts(trazodone,valdecoxib,deep_vein_thromboses).
interacts(trazodone,mometasone,heart_attack).
interacts(trazodone,mometasone,apoplexy).
interacts(trazodone,mometasone,still_birth).
interacts(trazodone,pregabalin,cardiac_disease).
interacts(trazodone,pregabalin,still_birth).
interacts(trazodone,ezetimibe,angina).
interacts(trazodone,ezetimibe,extremity_pain).
interacts(trazodone,ezetimibe,still_birth).
interacts(trazodone,varenicline,anxiety).
interacts(trazodone,varenicline,chest_pain).
interacts(trazodone,varenicline,acid_reflux).
interacts(trazodone,varenicline,cardiac_disease).
interacts(trazodone,varenicline,elevated_cholesterol).
interacts(trazodone,montelukast,transient_ischaemic_attack).
interacts(trazodone,montelukast,cough).
interacts(trazodone,montelukast,acid_reflux).
interacts(trazodone,montelukast,cardiac_disease).
interacts(trazodone,montelukast,heart_attack).
interacts(trazodone,montelukast,apoplexy).
interacts(triamcinolone,venlafaxine,attempted_suicide).
interacts(triamcinolone,venlafaxine,insomnia).
interacts(triamcinolone,zolpidem,anxiety).
interacts(triamcinolone,warfarin,anaemia).
interacts(triamcinolone,medroxyprogesterone,breast_cancer).
interacts(triamcinolone,megestrol,difficulty_breathing).
interacts(triamcinolone,cromolyn,asthma).
interacts(triamcinolone,clobetasol,asthma).
interacts(triamcinolone,clobetasol,difficulty_breathing).
interacts(triamcinolone,clobetasol,neumonia).
interacts(triamcinolone,simvastatin,angina).
interacts(triamcinolone,tiotropium,asthma).
interacts(triamcinolone,duloxetine,anxiety).
interacts(triamcinolone,olopatadine,asthma).
interacts(triamcinolone,fluticasone,difficulty_breathing).
interacts(triamcinolone,rosiglitazone,asthma).
interacts(triamcinolone,rosiglitazone,difficulty_breathing).
interacts(triamcinolone,rosiglitazone,hypoglycaemia).
interacts(triamcinolone,valdecoxib,heart_attack).
interacts(triamcinolone,desloratadine,cough).
interacts(triamcinolone,desloratadine,wheeze).
interacts(triamcinolone,desloratadine,dysphonia).
interacts(triamcinolone,nystatin,asthma).
interacts(triamcinolone,nystatin,difficulty_breathing).
interacts(triamcinolone,rosuvastatin,difficulty_breathing).
interacts(triamcinolone,montelukast,neumonia).
interacts(triamcinolone,montelukast,aptyalism).
interacts(triamcinolone,sucralfate,difficulty_breathing).
interacts(triamcinolone,pimecrolimus,asthma).
interacts(triamcinolone,pimecrolimus,cough).
interacts(triazolam,ursodeoxycholic_acid,neutropenia).
interacts(triazolam,valacyclovir,insomnia).
interacts(triazolam,valsartan,insomnia).
interacts(triazolam,venlafaxine,convulsion).
interacts(triazolam,zolpidem,diabetes).
interacts(triazolam,zolpidem,apoplexy).
interacts(triazolam,warfarin,kidney_failure).
interacts(triazolam,warfarin,bradycardia).
interacts(triazolam,isosorbide-5-mononitrate,apoplexy).
interacts(triazolam,simvastatin,apoplexy).
interacts(triazolam,clarithromycin,heart_attack).
interacts(triazolam,aripiprazole,pancreatitis).
interacts(triazolam,allopurinol,high_blood_pressure).
interacts(triazolam,lactulose,insomnia).
interacts(triazolam,montelukast,asthma).
interacts(trihexyphenidyl,zolpidem,anxiety).
interacts(trihexyphenidyl,lithium,diabetes).
interacts(trihexyphenidyl,aripiprazole,diabetic_acidosis).
interacts(trimethoprim,vincristine,thrombocytopenia).
interacts(trimethoprim,warfarin,aseptic_necrosis_bone).
interacts(trimethoprim,isosorbide-5-mononitrate,heart_attack).
interacts(trimethoprim,simvastatin,heart_attack).
interacts(trimethoprim,tiotropium,cough).
interacts(trimethoprim,lactulose,emesis).
interacts(trimethoprim,solifenacin_succinate,infection_urinary_tract).
interacts(ursodeoxycholic_acid,valsartan,arterial_pressure_nos_increased).
interacts(ursodeoxycholic_acid,zolpidem,anorexia).
interacts(ursodeoxycholic_acid,zolpidem,heart_attack).
interacts(ursodeoxycholic_acid,zolpidem,apoplexy).
interacts(ursodeoxycholic_acid,warfarin,deep_vein_thromboses).
interacts(ursodeoxycholic_acid,isosorbide-5-mononitrate,anaemia).
interacts(ursodeoxycholic_acid,torasemide,thrombocytopenia).
interacts(ursodeoxycholic_acid,torasemide,loss_of_weight).
interacts(ursodeoxycholic_acid,simvastatin,apoplexy).
interacts(ursodeoxycholic_acid,adefovir_dipivoxil,thrombocytopenia).
interacts(ursodeoxycholic_acid,lactulose,anaemia).
interacts(ursodeoxycholic_acid,lactulose,thrombocytopenia).
interacts(ursodeoxycholic_acid,bosentan,anaemia).
interacts(ursodeoxycholic_acid,bosentan,hypoventilation).
interacts(ursodeoxycholic_acid,etv,neutropenia).
interacts(ursodeoxycholic_acid,nystatin,anaemia).
interacts(ursodeoxycholic_acid,montelukast,neumonia).
interacts(ursodeoxycholic_acid,sucralfate,dehydration).
interacts(valacyclovir,zolpidem,anxiety).
interacts(valacyclovir,zolpidem,hypoventilation).
interacts(valacyclovir,zolpidem,insomnia).
interacts(valacyclovir,warfarin,kidney_failure).
interacts(valacyclovir,warfarin,aseptic_necrosis_bone).
interacts(valacyclovir,simvastatin,arterial_pressure_nos_increased).
interacts(valacyclovir,levetiracetam,eruption).
interacts(valacyclovir,fluticasone,asthma).
interacts(valacyclovir,fluticasone,cough).
interacts(valacyclovir,fluticasone,difficulty_breathing).
interacts(valacyclovir,rosiglitazone,hyperglycaemia).
interacts(valacyclovir,olmesartan_medoxomil,feeling_unwell).
interacts(valacyclovir,ezetimibe,muscle_weakness).
interacts(valacyclovir,montelukast,asthma).
interacts(valacyclovir,montelukast,dysphonia).
interacts(valacyclovir,sucralfate,feeling_unwell).
interacts(valsartan,venlafaxine,anxiety).
interacts(valsartan,venlafaxine,high_blood_pressure).
interacts(valsartan,venlafaxine,insomnia).
interacts(valsartan,zaleplon,heart_attack).
interacts(valsartan,zolpidem,insomnia).
interacts(valsartan,zopiclone,arterial_pressure_nos_decreased).
interacts(valsartan,warfarin,anaemia).
interacts(valsartan,warfarin,cardiac_failure).
interacts(valsartan,warfarin,acute_kidney_failure).
interacts(valsartan,warfarin,heart_attack).
interacts(valsartan,warfarin,apoplexy).
interacts(valsartan,warfarin,bradycardia).
interacts(valsartan,warfarin,aseptic_necrosis_bone).
interacts(valsartan,isosorbide-5-mononitrate,high_blood_pressure).
interacts(valsartan,simvastatin,chest_pain).
interacts(valsartan,simvastatin,elevated_cholesterol).
interacts(valsartan,simvastatin,apoplexy).
interacts(valsartan,tamsulosin,arterial_pressure_nos_decreased).
interacts(valsartan,aripiprazole,mod).
interacts(valsartan,duloxetine,high_blood_pressure).
interacts(valsartan,capecitabine,bradycardia).
interacts(valsartan,telmisartan,angioedema).
interacts(valsartan,telmisartan,feeling_unwell).
interacts(valsartan,rosiglitazone,hypoglycaemia).
interacts(valsartan,rosiglitazone,loss_of_weight).
interacts(valsartan,allopurinol,afib).
interacts(valsartan,lactulose,dehydration).
interacts(valsartan,valdecoxib,arteriosclerotic_heart_disease).
interacts(valsartan,pregabalin,apoplexy).
interacts(valsartan,ezetimibe,heart_attack).
interacts(valsartan,lenalidomide,aseptic_necrosis_bone).
interacts(valsartan,nystatin,high_blood_pressure).
interacts(valsartan,rosuvastatin,heart_attack).
interacts(valsartan,bimatoprost,arterial_pressure_nos_increased).
interacts(valsartan,montelukast,dysphonia).
interacts(valsartan,aliskiren,high_blood_pressure).
interacts(vancomycin,zolpidem,insomnia).
interacts(vancomycin,vincristine,thrombocytopenia).
interacts(vancomycin,warfarin,cardiac_decompensation).
interacts(vancomycin,warfarin,kidney_failure).
interacts(vancomycin,dobutamine,body_temperature_increased).
interacts(vancomycin,octreotide,hypokalaemia).
interacts(vancomycin,octreotide,septic_shock).
interacts(vancomycin,levetiracetam,lyell).
interacts(vancomycin,levetiracetam,convulsion).
interacts(vancomycin,fluticasone,chronic_obstructive_airway_disease).
interacts(vancomycin,valganciclovir,infection).
interacts(vancomycin,zoledronic_acid,thrombocytopenia).
interacts(vancomycin,voriconazole,lyell).
interacts(vancomycin,voriconazole,body_temperature_increased).
interacts(vancomycin,voriconazole,bone_marrow_failure).
interacts(vancomycin,rosiglitazone,hyperglycaemia).
interacts(vancomycin,rosiglitazone,hypoglycaemia).
interacts(vancomycin,rosiglitazone,loss_of_weight).
interacts(vancomycin,clofarabine,thrombocytopenia).
interacts(vancomycin,nitric_oxide,neutropenia).
interacts(vancomycin,ezetimibe,aching_muscles).
interacts(vancomycin,neomycin,pleural_effusion).
interacts(vancomycin,neomycin,thrombocytopenia).
interacts(vancomycin,sevelamer,sepsis).
interacts(vancomycin,nystatin,septic_shock).
interacts(vancomycin,tigecycline,neutropenia).
interacts(vancomycin,caspofungin,neutropenia).
interacts(vancomycin,caspofungin,pleural_effusion).
interacts(vancomycin,caspofungin,respiratory_failure).
interacts(vancomycin,rifampicin,bone_marrow_failure).
interacts(vancomycin,rifampicin,sepsis).
interacts(vancomycin,tenofovir_disoproxil_fumarate,eruption).
interacts(vancomycin,tenofovir_disoproxil_fumarate,aspartate_aminotransferase_increase).
interacts(venlafaxine,zolmitriptan,anxiety).
interacts(venlafaxine,zolpidem,head_ache).
interacts(venlafaxine,zolpidem,apoplexy).
interacts(venlafaxine,zonisamide,attempted_suicide).
interacts(venlafaxine,medroxyprogesterone,bleeding_vaginal).
interacts(venlafaxine,medroxyprogesterone,insomnia).
interacts(venlafaxine,megestrol,nausea).
interacts(venlafaxine,isosorbide-5-mononitrate,diabetes).
interacts(venlafaxine,lithium,anxiety).
interacts(venlafaxine,lithium,pancreatitis).
interacts(venlafaxine,oxcarbazepine,epilepsy).
interacts(venlafaxine,torasemide,tremor).
interacts(venlafaxine,simvastatin,arteriosclerotic_heart_disease).
interacts(venlafaxine,simvastatin,heart_attack).
interacts(venlafaxine,simvastatin,muscle_spasm).
interacts(venlafaxine,atomoxetine,weight_gain).
interacts(venlafaxine,atomoxetine,agitated).
interacts(venlafaxine,tamsulosin,arteriosclerotic_heart_disease).
interacts(venlafaxine,tamsulosin,heart_attack).
interacts(venlafaxine,tamsulosin,hypoventilation).
interacts(venlafaxine,aripiprazole,attempted_suicide).
interacts(venlafaxine,aripiprazole,agitated).
interacts(venlafaxine,aripiprazole,hypoventilation).
interacts(venlafaxine,tiotropium,asthma).
interacts(venlafaxine,tiotropium,attempted_suicide).
interacts(venlafaxine,duloxetine,amnesia).
interacts(venlafaxine,duloxetine,tremor).
interacts(venlafaxine,duloxetine,agitated).
interacts(venlafaxine,duloxetine,blurred_vision).
interacts(venlafaxine,ziprasidone,atrial_septal_defect).
interacts(venlafaxine,olopatadine,convulsion).
interacts(venlafaxine,fluticasone,attempted_suicide).
interacts(venlafaxine,fluticasone,agitated).
interacts(venlafaxine,fluticasone,insomnia).
interacts(venlafaxine,acamprosate,agitated).
interacts(venlafaxine,eletriptan,loss_of_weight).
interacts(venlafaxine,rosiglitazone,diabetes).
interacts(venlafaxine,rosiglitazone,hyperglycaemia).
interacts(venlafaxine,rosiglitazone,hypoglycaemia).
interacts(venlafaxine,allopurinol,high_blood_pressure).
interacts(venlafaxine,lactulose,tremor).
interacts(venlafaxine,bortezomib,anxiety).
interacts(venlafaxine,bortezomib,hypoventilation).
interacts(venlafaxine,vardenafil,anxiety).
interacts(venlafaxine,valdecoxib,high_blood_pressure).
interacts(venlafaxine,valdecoxib,heart_attack).
interacts(venlafaxine,valdecoxib,apoplexy).
interacts(venlafaxine,mometasone,diabetes).
interacts(venlafaxine,desloratadine,bruxism).
interacts(venlafaxine,desloratadine,attempted_suicide).
interacts(venlafaxine,pregabalin,attempted_suicide).
interacts(venlafaxine,ezetimibe,heart_attack).
interacts(venlafaxine,varenicline,asthma).
interacts(venlafaxine,varenicline,attempted_suicide).
interacts(venlafaxine,glatiramer_acetate,agitated).
interacts(venlafaxine,glatiramer_acetate,insomnia).
interacts(venlafaxine,rosuvastatin,heart_attack).
interacts(venlafaxine,rosuvastatin,apoplexy).
interacts(venlafaxine,rosuvastatin,tinnitus).
interacts(venlafaxine,tenofovir_disoproxil_fumarate,attempted_suicide).
interacts(venlafaxine,sucralfate,attempted_suicide).
interacts(vinorelbine,zolpidem,insomnia).
interacts(vinorelbine,warfarin,anaemia).
interacts(vinorelbine,warfarin,acute_kidney_failure).
interacts(vinorelbine,carboplatin,neutropenia).
interacts(vinorelbine,carboplatin,pleural_effusion).
interacts(vinorelbine,carboplatin,thrombocytopenia).
interacts(vinorelbine,carboplatin,emesis).
interacts(vinorelbine,zoledronic_acid,neutropenia).
interacts(vinorelbine,cisplatin,anorexia).
interacts(vinorelbine,cisplatin,body_temperature_increased).
interacts(vinorelbine,cisplatin,leucopenia).
interacts(vinorelbine,cisplatin,bone_marrow_failure).
interacts(vinorelbine,cisplatin,pleural_effusion).
interacts(vinorelbine,cisplatin,mucositis_oral).
interacts(vinorelbine,cisplatin,sepsis).
interacts(vinorelbine,cisplatin,aseptic_necrosis_bone).
interacts(zafirlukast,zolpidem,insomnia).
interacts(zafirlukast,tiotropium,bronchial_spasm).
interacts(zafirlukast,tiotropium,pain_in_throat).
interacts(zafirlukast,fluticasone,aptyalism).
interacts(zafirlukast,montelukast,difficulty_breathing).
interacts(zafirlukast,montelukast,muscle_spasm).
interacts(zaleplon,rosiglitazone,nausea).
interacts(zaleplon,valdecoxib,arteriosclerotic_heart_disease).
interacts(zolmitriptan,zolpidem,insomnia).
interacts(zolmitriptan,simvastatin,high_blood_pressure).
interacts(zolpidem,warfarin,anxiety).
interacts(zolpidem,warfarin,high_blood_pressure).
interacts(zolpidem,warfarin,heart_attack).
interacts(zolpidem,medroxyprogesterone,apoplexy).
interacts(zolpidem,amiloride,pain).
interacts(zolpidem,megestrol,heart_attack).
interacts(zolpidem,isosorbide-5-mononitrate,apoplexy).
interacts(zolpidem,isosorbide-5-mononitrate,hypoventilation).
interacts(zolpidem,isosorbide-5-mononitrate,insomnia).
interacts(zolpidem,lithium,diabetes).
interacts(zolpidem,lithium,elevated_cholesterol).
interacts(zolpidem,oxcarbazepine,drowsiness).
interacts(zolpidem,oxcarbazepine,insomnia).
interacts(zolpidem,acarbose,pain).
interacts(zolpidem,acarbose,insomnia).
interacts(zolpidem,clarithromycin,apoplexy).
interacts(zolpidem,atomoxetine,tremor).
interacts(zolpidem,levetiracetam,muscle_spasm).
interacts(zolpidem,levetiracetam,attempted_suicide).
interacts(zolpidem,levetiracetam,insomnia).
interacts(zolpidem,tamsulosin,chest_pain).
interacts(zolpidem,tamsulosin,arteriosclerotic_heart_disease).
interacts(zolpidem,tamsulosin,insomnia).
interacts(zolpidem,perindopril,dizziness).
interacts(zolpidem,perindopril,apoplexy).
interacts(zolpidem,tiotropium,anxiety).
interacts(zolpidem,tiotropium,asthma).
interacts(zolpidem,duloxetine,confusion).
interacts(zolpidem,duloxetine,insomnia).
interacts(zolpidem,pemetrexed,insomnia).
interacts(zolpidem,ibandronate,anorexia).
interacts(zolpidem,ziprasidone,apoplexy).
interacts(zolpidem,ziprasidone,insomnia).
interacts(zolpidem,olopatadine,apoplexy).
interacts(zolpidem,telmisartan,insomnia).
interacts(zolpidem,zoledronic_acid,insomnia).
interacts(zolpidem,dofetilide,apoplexy).
interacts(zolpidem,dofetilide,hypoventilation).
interacts(zolpidem,dofetilide,insomnia).
interacts(zolpidem,voriconazole,agitated).
interacts(zolpidem,voriconazole,hypoventilation).
interacts(zolpidem,voriconazole,insomnia).
interacts(zolpidem,rosiglitazone,chest_pain).
interacts(zolpidem,allopurinol,high_blood_pressure).
interacts(zolpidem,allopurinol,heart_attack).
interacts(zolpidem,allopurinol,insomnia).
interacts(zolpidem,lactulose,anxiety).
interacts(zolpidem,lactulose,chest_pain).
interacts(zolpidem,lactulose,insomnia).
interacts(zolpidem,bortezomib,aseptic_necrosis_bone).
interacts(zolpidem,bortezomib,insomnia).
interacts(zolpidem,bosentan,insomnia).
interacts(zolpidem,vardenafil,apoplexy).
interacts(zolpidem,tadalafil,heart_attack).
interacts(zolpidem,tadalafil,pain).
interacts(zolpidem,tadalafil,apoplexy).
interacts(zolpidem,tadalafil,insomnia).
interacts(zolpidem,valdecoxib,osteoarthritis).
interacts(zolpidem,valdecoxib,apoplexy).
interacts(zolpidem,mometasone,heart_attack).
interacts(zolpidem,mometasone,apoplexy).
interacts(zolpidem,mometasone,insomnia).
interacts(zolpidem,gefitinib,anxiety).
interacts(zolpidem,gefitinib,insomnia).
interacts(zolpidem,desloratadine,high_blood_pressure).
interacts(zolpidem,desloratadine,panic_attack).
interacts(zolpidem,desloratadine,hypoventilation).
interacts(zolpidem,pregabalin,anxiety).
interacts(zolpidem,pregabalin,insomnia).
interacts(zolpidem,olmesartan_medoxomil,heart_attack).
interacts(zolpidem,olmesartan_medoxomil,insomnia).
interacts(zolpidem,palonosetron,anxiety).
interacts(zolpidem,palonosetron,hypoventilation).
interacts(zolpidem,palonosetron,insomnia).
interacts(zolpidem,ezetimibe,back_ache).
interacts(zolpidem,ezetimibe,elevated_cholesterol).
interacts(zolpidem,ezetimibe,high_blood_pressure).
interacts(zolpidem,ezetimibe,apoplexy).
interacts(zolpidem,aprepitant,anxiety).
interacts(zolpidem,dutasteride,heart_attack).
interacts(zolpidem,varenicline,drowsiness).
interacts(zolpidem,varenicline,pain).
interacts(zolpidem,sorafenib,hallucination).
interacts(zolpidem,sorafenib,insomnia).
interacts(zolpidem,lenalidomide,insomnia).
interacts(zolpidem,nateglinide,apoplexy).
interacts(zolpidem,nateglinide,insomnia).
interacts(zolpidem,telithromycin,agitated).
interacts(zolpidem,glatiramer_acetate,high_blood_pressure).
interacts(zolpidem,glatiramer_acetate,heart_attack).
interacts(zolpidem,sevelamer,anxiety).
interacts(zolpidem,sevelamer,insomnia).
interacts(zolpidem,nystatin,agitated).
interacts(zolpidem,misoprostol,apoplexy).
interacts(zolpidem,rosuvastatin,aching_joints).
interacts(zolpidem,rosuvastatin,extremity_pain).
interacts(zolpidem,rosuvastatin,abdominal_pain_upper).
interacts(zolpidem,paricalcitol,heart_attack).
interacts(zolpidem,bimatoprost,insomnia).
interacts(zolpidem,montelukast,arteriosclerotic_heart_disease).
interacts(zolpidem,montelukast,heart_attack).
interacts(zolpidem,montelukast,insomnia).
interacts(zolpidem,su11248,drowsiness).
interacts(zolpidem,tegaserod,heart_attack).
interacts(zolpidem,tegaserod,insomnia).
interacts(zolpidem,icl670,chest_pain).
interacts(zolpidem,icl670,high_blood_pressure).
interacts(zolpidem,sucralfate,apoplexy).
interacts(zolpidem,sucralfate,insomnia).
interacts(zonisamide,warfarin,arterial_pressure_nos_decreased).
interacts(zonisamide,oxcarbazepine,status_epilepticus).
interacts(zonisamide,levetiracetam,lyell).
interacts(zonisamide,levetiracetam,eruption).
interacts(zonisamide,duloxetine,convulsion).
interacts(zopiclone,lithium,mod).
interacts(zopiclone,carboplatin,neutropenia).
interacts(zopiclone,tamsulosin,cardiac_disease).
interacts(zopiclone,aripiprazole,mod).
interacts(zopiclone,aripiprazole,weight_gain).
interacts(zopiclone,tiotropium,difficulty_breathing).
interacts(zopiclone,fluticasone,chest_pain).
interacts(zopiclone,fluticasone,diabetes).
interacts(zopiclone,rosiglitazone,amnesia).
interacts(zopiclone,rosiglitazone,diabetes).
interacts(zopiclone,allopurinol,apoplexy).
interacts(zopiclone,montelukast,cough).
interacts(zopiclone,sucralfate,muscle_spasm).
interacts(mitomycin_c,cisplatin,anaemia).
interacts(vincristine,warfarin,cardiac_decompensation).
interacts(vincristine,warfarin,bone_marrow_failure).
interacts(vincristine,sodium_bicarbonate,neutropenia).
interacts(vincristine,sodium_bicarbonate,aseptic_necrosis_bone).
interacts(vincristine,carboplatin,bone_marrow_failure).
interacts(vincristine,carboplatin,neuropathy_peripheral).
interacts(vincristine,carboplatin,neumonia).
interacts(vincristine,simvastatin,arteriosclerotic_heart_disease).
interacts(vincristine,zoledronic_acid,leucopenia).
interacts(vincristine,voriconazole,neutropenia).
interacts(vincristine,allopurinol,arterial_pressure_nos_decreased).
interacts(vincristine,allopurinol,aseptic_necrosis_bone).
interacts(vincristine,lactulose,infection).
interacts(vincristine,lactulose,neutropenia).
interacts(vincristine,mercaptopurine,neutropenia).
interacts(vincristine,nystatin,bone_marrow_failure).
interacts(vincristine,nystatin,sepsis).
interacts(vincristine,cisplatin,neuropathy_peripheral).
interacts(vincristine,cisplatin,septic_shock).
interacts(vincristine,cisplatin,thrombocytopenia).
interacts(warfarin,sodium_bicarbonate,neumonia).
interacts(warfarin,sodium_bicarbonate,kidney_failure).
interacts(warfarin,medroxyprogesterone,anaemia).
interacts(warfarin,amiloride,difficulty_breathing).
interacts(warfarin,megestrol,cardiac_decompensation).
interacts(warfarin,calcium_chloride,aseptic_necrosis_bone).
interacts(warfarin,isosorbide-5-mononitrate,anaemia).
interacts(warfarin,isosorbide-5-mononitrate,arteriosclerotic_heart_disease).
interacts(warfarin,isosorbide-5-mononitrate,arterial_pressure_nos_decreased).
interacts(warfarin,isosorbide-5-mononitrate,kidney_failure).
interacts(warfarin,isosorbide-5-mononitrate,bradycardia).
interacts(warfarin,lithium,pancreatitis).
interacts(warfarin,clobetasol,anaemia).
interacts(warfarin,oxcarbazepine,aseptic_necrosis_bone).
interacts(warfarin,torasemide,anaemia).
interacts(warfarin,torasemide,arterial_pressure_nos_decreased).
interacts(warfarin,goserelin,multiple_myeloma).
interacts(warfarin,octreotide,cardiac_failure).
interacts(warfarin,simvastatin,arrhythmia).
interacts(warfarin,simvastatin,asthenia).
interacts(warfarin,simvastatin,chest_pain).
interacts(warfarin,simvastatin,arteriosclerotic_heart_disease).
interacts(warfarin,simvastatin,cardiac_disease).
interacts(warfarin,simvastatin,cardiac_failure).
interacts(warfarin,simvastatin,excess_potassium).
interacts(warfarin,simvastatin,osteoarthritis).
interacts(warfarin,simvastatin,apoplexy).
interacts(warfarin,simvastatin,tachycardia_ventricular).
interacts(warfarin,simvastatin,cardiac_ischemia).
interacts(warfarin,simvastatin,bradycardia).
interacts(warfarin,simvastatin,aseptic_necrosis_bone).
interacts(warfarin,clarithromycin,cardiac_decompensation).
interacts(warfarin,clarithromycin,aseptic_necrosis_bone).
interacts(warfarin,atomoxetine,chest_pain).
interacts(warfarin,ranolazine,afib).
interacts(warfarin,levetiracetam,anaemia).
interacts(warfarin,tamsulosin,anaemia).
interacts(warfarin,exemestane,cardiac_decompensation).
interacts(warfarin,aripiprazole,aseptic_necrosis_bone).
interacts(warfarin,pemetrexed,cardiac_decompensation).
interacts(warfarin,ibandronate,arterial_pressure_nos_decreased).
interacts(warfarin,ibandronate,aseptic_necrosis_bone).
interacts(warfarin,fluticasone,asthma).
interacts(warfarin,fluticasone,cardiac_decompensation).
interacts(warfarin,telmisartan,afib).
interacts(warfarin,telmisartan,acute_kidney_failure).
interacts(warfarin,zoledronic_acid,thrombocytopenia).
interacts(warfarin,voriconazole,aseptic_necrosis_bone).
interacts(warfarin,darifenacin,aseptic_necrosis_bone).
interacts(warfarin,rosiglitazone,anorexia).
interacts(warfarin,rosiglitazone,cardiac_failure).
interacts(warfarin,rosiglitazone,hyperglycaemia).
interacts(warfarin,rosiglitazone,hypoglycaemia).
interacts(warfarin,rosiglitazone,apoplexy).
interacts(warfarin,rosiglitazone,loss_of_weight).
interacts(warfarin,allopurinol,arrhythmia).
interacts(warfarin,allopurinol,difficulty_breathing).
interacts(warfarin,allopurinol,excess_potassium).
interacts(warfarin,allopurinol,arterial_pressure_nos_decreased).
interacts(warfarin,allopurinol,heart_attack).
interacts(warfarin,allopurinol,edema_extremities).
interacts(warfarin,allopurinol,bradycardia).
interacts(warfarin,allopurinol,aseptic_necrosis_bone).
interacts(warfarin,lactulose,cardiac_decompensation).
interacts(warfarin,lactulose,heart_attack).
interacts(warfarin,lactulose,bradycardia).
interacts(warfarin,valdecoxib,transient_ischaemic_attack).
interacts(warfarin,valdecoxib,chest_pain).
interacts(warfarin,valdecoxib,cardiac_failure).
interacts(warfarin,valdecoxib,cardiac_decompensation).
interacts(warfarin,valdecoxib,heart_attack).
interacts(warfarin,mometasone,cardiac_decompensation).
interacts(warfarin,gefitinib,aseptic_necrosis_bone).
interacts(warfarin,olmesartan_medoxomil,anaemia).
interacts(warfarin,ezetimibe,cardiac_decompensation).
interacts(warfarin,ezetimibe,heart_attack).
interacts(warfarin,aprepitant,anaemia).
interacts(warfarin,dutasteride,aseptic_necrosis_bone).
interacts(warfarin,cinacalcet,bradycardia).
interacts(warfarin,colesevelam_hydrochloride,heart_attack).
interacts(warfarin,lambda,cardiac_decompensation).
interacts(warfarin,ambrisentan,anaemia).
interacts(warfarin,lenalidomide,difficulty_breathing).
interacts(warfarin,telithromycin,anaemia).
interacts(warfarin,glatiramer_acetate,cardiac_decompensation).
interacts(warfarin,sevelamer,cardiac_failure).
interacts(warfarin,sevelamer,arterial_pressure_nos_decreased).
interacts(warfarin,nystatin,anaemia).
interacts(warfarin,nystatin,cardiac_failure).
interacts(warfarin,paricalcitol,bradycardia).
interacts(warfarin,bimatoprost,acute_kidney_failure).
interacts(warfarin,cisplatin,aseptic_necrosis_bone).
interacts(warfarin,eptifibatide,anaemia).
interacts(warfarin,iloprost,arterial_pressure_nos_decreased).
interacts(warfarin,iloprost,edema_extremities).
interacts(warfarin,montelukast,cardiac_failure).
interacts(warfarin,montelukast,apoplexy).
interacts(warfarin,montelukast,aseptic_necrosis_bone).
interacts(warfarin,su11248,cardiac_decompensation).
interacts(warfarin,su11248,acute_kidney_failure).
interacts(warfarin,rifampicin,arterial_pressure_nos_decreased).
interacts(warfarin,tenofovir_disoproxil_fumarate,cardiac_decompensation).
interacts(warfarin,icl670,aseptic_necrosis_bone).
interacts(warfarin,aliskiren,kidney_failure).
interacts(warfarin,cefdinir,arterial_pressure_nos_decreased).
interacts(sodium_bicarbonate,torasemide,excess_potassium).
interacts(sodium_bicarbonate,torasemide,kidney_failure).
interacts(sodium_bicarbonate,simvastatin,apoplexy).
interacts(sodium_bicarbonate,lactulose,anaemia).
interacts(sodium_bicarbonate,bortezomib,osteomyelitis).
interacts(sodium_bicarbonate,sevelamer,blood_calcium_decreased).
interacts(sodium_bicarbonate,sevelamer,peritonitis).
interacts(sodium_bicarbonate,sevelamer,aplasia_pure_red_cell).
interacts(sodium_bicarbonate,nystatin,anaemia).
interacts(sodium_bicarbonate,nystatin,blood_calcium_decreased).
interacts(sodium_bicarbonate,nystatin,neutropenia).
interacts(sodium_bicarbonate,paricalcitol,blood_calcium_decreased).
interacts(sodium_bicarbonate,paricalcitol,aplasia_pure_red_cell).
interacts(sodium_bicarbonate,cisplatin,bone_marrow_failure).
interacts(sodium_bicarbonate,cisplatin,neumonia).
interacts(acenocoumarol,torasemide,afib).
interacts(acenocoumarol,torasemide,drug_toxicity_nos).
interacts(medroxyprogesterone,simvastatin,angina).
interacts(medroxyprogesterone,simvastatin,apoplexy).
interacts(medroxyprogesterone,tiotropium,asthma).
interacts(medroxyprogesterone,fluticasone,breast_cancer).
interacts(medroxyprogesterone,rosiglitazone,hyperglycaemia).
interacts(medroxyprogesterone,valdecoxib,high_blood_pressure).
interacts(medroxyprogesterone,ezetimibe,muscle_spasm).
interacts(medroxyprogesterone,nystatin,adenocarcinoma).
interacts(medroxyprogesterone,montelukast,difficulty_breathing).
interacts(medroxyprogesterone,montelukast,wheeze).
interacts(vinblastine,dacarbazine,body_temperature_increased).
interacts(megestrol,isosorbide-5-mononitrate,heart_attack).
interacts(megestrol,carboplatin,aseptic_necrosis_bone).
interacts(megestrol,tamsulosin,chest_pain).
interacts(megestrol,fluticasone,difficulty_breathing).
interacts(megestrol,zoledronic_acid,multiple_myeloma).
interacts(megestrol,zoledronic_acid,neutropenia).
interacts(megestrol,rosiglitazone,anorexia).
interacts(megestrol,rosiglitazone,hyperglycaemia).
interacts(megestrol,lactulose,dehydration).
interacts(megestrol,lactulose,sepsis).
interacts(megestrol,bortezomib,infection).
interacts(megestrol,bortezomib,multiple_myeloma).
interacts(megestrol,gefitinib,anorexia).
interacts(megestrol,erlotinib,dehydration).
interacts(megestrol,lenalidomide,neuropathy_peripheral).
interacts(megestrol,sevelamer,anaemia).
interacts(megestrol,sevelamer,dehydration).
interacts(megestrol,cisplatin,body_temperature_increased).
interacts(megestrol,montelukast,cough).
interacts(megestrol,su11248,neutropenia).
interacts(megestrol,tenofovir_disoproxil_fumarate,body_temperature_increased).
interacts(selenium_sulfide,simvastatin,aching_muscles).
interacts(calcium_chloride,simvastatin,high_blood_pressure).
interacts(calcium_chloride,simvastatin,aseptic_necrosis_bone).
interacts(isosorbide-5-mononitrate,carboplatin,heart_attack).
interacts(isosorbide-5-mononitrate,acarbose,apoplexy).
interacts(isosorbide-5-mononitrate,simvastatin,osteoarthritis).
interacts(isosorbide-5-mononitrate,clarithromycin,cardiac_disease).
interacts(isosorbide-5-mononitrate,perindopril,heart_attack).
interacts(isosorbide-5-mononitrate,tiotropium,asthma).
interacts(isosorbide-5-mononitrate,duloxetine,heart_attack).
interacts(isosorbide-5-mononitrate,rosiglitazone,hypoglycaemia).
interacts(isosorbide-5-mononitrate,rosiglitazone,loss_of_weight).
interacts(isosorbide-5-mononitrate,allopurinol,cardiac_disease).
interacts(isosorbide-5-mononitrate,allopurinol,hyperglycaemia).
interacts(isosorbide-5-mononitrate,lactulose,chest_pain).
interacts(isosorbide-5-mononitrate,lactulose,hyperglycaemia).
interacts(isosorbide-5-mononitrate,lactulose,heart_attack).
interacts(isosorbide-5-mononitrate,valdecoxib,arteriosclerotic_heart_disease).
interacts(isosorbide-5-mononitrate,valdecoxib,high_blood_pressure).
interacts(isosorbide-5-mononitrate,valdecoxib,apoplexy).
interacts(isosorbide-5-mononitrate,ezetimibe,elevated_cholesterol).
interacts(isosorbide-5-mononitrate,ezetimibe,muscle_spasm).
interacts(isosorbide-5-mononitrate,sevelamer,arteriosclerotic_heart_disease).
interacts(isosorbide-5-mononitrate,montelukast,cardiac_disease).
interacts(isosorbide-5-mononitrate,tegaserod,arteriosclerotic_heart_disease).
interacts(cromolyn,tiotropium,cough).
interacts(cromolyn,fluticasone,cough).
interacts(cromolyn,fluticasone,difficulty_breathing).
interacts(cromolyn,fluticasone,neumonia).
interacts(cromolyn,fluticasone,dysphonia).
interacts(lithium,oxcarbazepine,abortion_spontaneous).
interacts(lithium,oxcarbazepine,diabetes).
interacts(lithium,oxcarbazepine,mod).
interacts(lithium,oxcarbazepine,loss_of_consciousness).
interacts(lithium,simvastatin,chest_pain).
interacts(lithium,simvastatin,high_blood_pressure).
interacts(lithium,aripiprazole,pancreatitis).
interacts(lithium,aripiprazole,loss_of_consciousness).
interacts(lithium,aripiprazole,ketoacidosis).
interacts(lithium,tiotropium,asthma).
interacts(lithium,duloxetine,drowsiness).
interacts(lithium,duloxetine,weight_gain).
interacts(lithium,duloxetine,blurred_vision).
interacts(lithium,ziprasidone,diabetes).
interacts(lithium,ziprasidone,pancreatitis).
interacts(lithium,allopurinol,diabetes).
interacts(lithium,allopurinol,hyperglycaemia).
interacts(lithium,allopurinol,heart_attack).
interacts(lithium,pregabalin,attempted_suicide).
interacts(lithium,montelukast,diabetes).
interacts(clobetasol,fluticasone,cough).
interacts(clobetasol,fluticasone,difficulty_breathing).
interacts(clobetasol,montelukast,asthma).
interacts(oxcarbazepine,simvastatin,elevated_cholesterol).
interacts(oxcarbazepine,levetiracetam,lyell).
interacts(oxcarbazepine,levetiracetam,eruption).
interacts(oxcarbazepine,tamsulosin,heart_attack).
interacts(oxcarbazepine,aripiprazole,pancreatitis).
interacts(oxcarbazepine,duloxetine,diabetes).
interacts(oxcarbazepine,ziprasidone,diabetic_acidosis).
interacts(oxcarbazepine,ziprasidone,pancreatitis).
interacts(oxcarbazepine,ziprasidone,ketoacidosis).
interacts(oxcarbazepine,fluticasone,difficulty_breathing).
interacts(oxcarbazepine,rosiglitazone,loss_of_weight).
interacts(oxcarbazepine,ezetimibe,aching_muscles).
interacts(oxcarbazepine,varenicline,epilepsy).
interacts(oxcarbazepine,rosuvastatin,apoplexy).
interacts(etomidate,rocuronium,anaphylactic_reaction).
interacts(etomidate,rocuronium,metabolic_acidosis).
interacts(carboplatin,pemetrexed,aseptic_necrosis_bone).
interacts(carboplatin,zoledronic_acid,thrombocytopenia).
interacts(carboplatin,allopurinol,blood_sodium_decreased).
interacts(carboplatin,lactulose,sepsis).
interacts(carboplatin,lactulose,aseptic_necrosis_bone).
interacts(carboplatin,palonosetron,neumonia).
interacts(carboplatin,aprepitant,neutropenia).
interacts(carboplatin,aprepitant,aseptic_necrosis_bone).
interacts(carboplatin,erlotinib,thrombocytopenia).
interacts(carboplatin,misoprostol,neutropenia).
interacts(carboplatin,cisplatin,anaemia).
interacts(carboplatin,cisplatin,neutropenia).
interacts(carboplatin,cisplatin,neumonia).
interacts(sufentanil,cisatracurium,anaphylactic_reaction).
interacts(sufentanil,cisatracurium,asystole).
interacts(sufentanil,rocuronium,bronchial_spasm).
interacts(acarbose,simvastatin,apoplexy).
interacts(acarbose,rosiglitazone,ecchymoses).
interacts(acarbose,rosiglitazone,hyperglycaemia).
interacts(acarbose,rosiglitazone,hypoglycaemia).
interacts(acarbose,rosiglitazone,loss_of_weight).
interacts(torasemide,tiotropium,dysphonia).
interacts(torasemide,fluticasone,asthma).
interacts(torasemide,fluticasone,difficulty_breathing).
interacts(torasemide,rosiglitazone,acidosis).
interacts(torasemide,rosiglitazone,hyperglycaemia).
interacts(torasemide,rosiglitazone,hypoglycaemia).
interacts(torasemide,rosiglitazone,nausea).
interacts(torasemide,rosiglitazone,loss_of_weight).
interacts(torasemide,allopurinol,arterial_pressure_nos_decreased).
interacts(torasemide,allopurinol,acute_kidney_failure).
interacts(torasemide,lactulose,dehydration).
interacts(torasemide,ambrisentan,cardiac_failure).
interacts(torasemide,aliskiren,high_blood_pressure).
interacts(torasemide,sucralfate,arterial_pressure_nos_decreased).
interacts(goserelin,tamsulosin,heart_attack).
interacts(octreotide,lactulose,acute_kidney_failure).
interacts(simvastatin,clarithromycin,chest_pain).
interacts(simvastatin,clarithromycin,arteriosclerotic_heart_disease).
interacts(simvastatin,clarithromycin,heart_attack).
interacts(simvastatin,atomoxetine,elevated_cholesterol).
interacts(simvastatin,perindopril,chest_pain).
interacts(simvastatin,perindopril,arteriosclerotic_heart_disease).
interacts(simvastatin,aripiprazole,apoplexy).
interacts(simvastatin,aripiprazole,aching_muscles).
interacts(simvastatin,duloxetine,dizziness).
interacts(simvastatin,ibandronate,muscle_spasm).
interacts(simvastatin,ziprasidone,heart_attack).
interacts(simvastatin,fluticasone,cardiac_disease).
interacts(simvastatin,fluticasone,aching_muscles).
interacts(simvastatin,telmisartan,arteriosclerotic_heart_disease).
interacts(simvastatin,telmisartan,apoplexy).
interacts(simvastatin,telmisartan,arterial_pressure_nos_increased).
interacts(simvastatin,zoledronic_acid,high_blood_pressure).
interacts(simvastatin,zoledronic_acid,aching_muscles).
interacts(simvastatin,dofetilide,arteriosclerotic_heart_disease).
interacts(simvastatin,dofetilide,apoplexy).
interacts(simvastatin,voriconazole,apoplexy).
interacts(simvastatin,voriconazole,aching_muscles).
interacts(simvastatin,rosiglitazone,angina).
interacts(simvastatin,rosiglitazone,high_blood_pressure).
interacts(simvastatin,rosiglitazone,extremity_pain).
interacts(simvastatin,rosiglitazone,apoplexy).
interacts(simvastatin,rosiglitazone,loss_of_weight).
interacts(simvastatin,allopurinol,arteriosclerotic_heart_disease).
interacts(simvastatin,allopurinol,difficulty_breathing).
interacts(simvastatin,allopurinol,cardiac_disease).
interacts(simvastatin,allopurinol,cardiac_failure).
interacts(simvastatin,allopurinol,cardiac_decompensation).
interacts(simvastatin,allopurinol,hyperglycaemia).
interacts(simvastatin,moexipril,elevated_cholesterol).
interacts(simvastatin,bortezomib,aseptic_necrosis_bone).
interacts(simvastatin,tadalafil,arteriosclerotic_heart_disease).
interacts(simvastatin,tadalafil,elevated_cholesterol).
interacts(simvastatin,valdecoxib,chronic_obstructive_airway_disease).
interacts(simvastatin,valdecoxib,osteoarthritis).
interacts(simvastatin,mometasone,elevated_cholesterol).
interacts(simvastatin,mometasone,high_blood_pressure).
interacts(simvastatin,pregabalin,high_blood_pressure).
interacts(simvastatin,olmesartan_medoxomil,chest_pain).
interacts(simvastatin,olmesartan_medoxomil,arteriosclerotic_heart_disease).
interacts(simvastatin,olmesartan_medoxomil,apoplexy).
interacts(simvastatin,eplerenone,arterial_pressure_nos_decreased).
interacts(simvastatin,ezetimibe,arteriosclerotic_heart_disease).
interacts(simvastatin,ezetimibe,elevated_cholesterol).
interacts(simvastatin,cinacalcet,extremity_pain).
interacts(simvastatin,sorafenib,aching_muscles).
interacts(simvastatin,lenalidomide,cardiac_disease).
interacts(simvastatin,mycophenolic_acid,arterial_pressure_nos_increased).
interacts(simvastatin,telithromycin,transient_ischaemic_attack).
interacts(simvastatin,telithromycin,chest_pain).
interacts(simvastatin,dasatinib,chest_pain).
interacts(simvastatin,glatiramer_acetate,aching_muscles).
interacts(simvastatin,sevelamer,muscle_spasm).
interacts(simvastatin,nystatin,dizziness).
interacts(simvastatin,rosuvastatin,chest_pain).
interacts(simvastatin,travoprost,arteriosclerotic_heart_disease).
interacts(simvastatin,bimatoprost,arteriosclerotic_heart_disease).
interacts(simvastatin,bimatoprost,elevated_cholesterol).
interacts(simvastatin,cisplatin,difficulty_breathing).
interacts(simvastatin,eptifibatide,chest_pain).
interacts(simvastatin,iloprost,cardiac_decompensation).
interacts(simvastatin,montelukast,angina).
interacts(simvastatin,montelukast,high_blood_pressure).
interacts(simvastatin,montelukast,heart_attack).
interacts(simvastatin,montelukast,apoplexy).
interacts(simvastatin,montelukast,aching_muscles).
interacts(simvastatin,su11248,apoplexy).
interacts(simvastatin,verteporfin,arteriosclerotic_heart_disease).
interacts(simvastatin,rifampicin,arteriosclerotic_heart_disease).
interacts(simvastatin,tegaserod,high_blood_pressure).
interacts(simvastatin,aliskiren,aching_muscles).
interacts(simvastatin,cefdinir,heart_attack).
interacts(cefpodoxime,montelukast,difficulty_breathing).
interacts(clarithromycin,tiotropium,asthma).
interacts(clarithromycin,tiotropium,difficulty_breathing).
interacts(clarithromycin,olopatadine,anxiety).
interacts(clarithromycin,fluticasone,pain_in_throat).
interacts(clarithromycin,rosiglitazone,loss_of_weight).
interacts(clarithromycin,lactulose,chest_pain).
interacts(clarithromycin,bortezomib,aseptic_necrosis_bone).
interacts(clarithromycin,rosuvastatin,heart_attack).
interacts(clarithromycin,montelukast,difficulty_breathing).
interacts(atomoxetine,aripiprazole,attempted_suicide).
interacts(atomoxetine,montelukast,asthma).
interacts(ranolazine,ezetimibe,chest_pain).
interacts(ranolazine,ezetimibe,elevated_cholesterol).
interacts(ranolazine,ezetimibe,muscle_spasm).
interacts(ranolazine,rosuvastatin,heart_attack).
interacts(n-0437,entacapone,bruxism).
interacts(levetiracetam,valganciclovir,convulsion).
interacts(levetiracetam,zoledronic_acid,eruption).
interacts(levetiracetam,lactulose,eruption).
interacts(tamsulosin,duloxetine,muscle_spasm).
interacts(tamsulosin,duloxetine,apoplexy).
interacts(tamsulosin,fluticasone,difficulty_breathing).
interacts(tamsulosin,fluticasone,heart_attack).
interacts(tamsulosin,rosiglitazone,apoplexy).
interacts(tamsulosin,rosiglitazone,loss_of_weight).
interacts(tamsulosin,allopurinol,arteriosclerotic_heart_disease).
interacts(tamsulosin,allopurinol,cardiac_decompensation).
interacts(tamsulosin,allopurinol,heart_attack).
interacts(tamsulosin,bortezomib,anaemia).
interacts(tamsulosin,valdecoxib,cardiac_disease).
interacts(tamsulosin,valdecoxib,high_blood_pressure).
interacts(tamsulosin,valdecoxib,heart_attack).
interacts(tamsulosin,desloratadine,apoplexy).
interacts(tamsulosin,olmesartan_medoxomil,arteriosclerotic_heart_disease).
interacts(tamsulosin,ezetimibe,muscle_spasm).
interacts(tamsulosin,lenalidomide,heart_attack).
interacts(tamsulosin,sucralfate,heart_attack).
interacts(perindopril,rosiglitazone,loss_of_weight).
interacts(perindopril,allopurinol,afib).
interacts(perindopril,lactulose,acute_kidney_failure).
interacts(perindopril,lactulose,heart_attack).
interacts(exemestane,zoledronic_acid,neuropathy_peripheral).
interacts(saquinavir,tenofovir_disoproxil_fumarate,acidosis).
interacts(saquinavir,tenofovir_disoproxil_fumarate,still_birth).
interacts(aripiprazole,9-hydroxyrisperidone,diabetes).
interacts(aripiprazole,ezetimibe,elevated_cholesterol).
interacts(aripiprazole,rosuvastatin,heart_attack).
interacts(aripiprazole,montelukast,diabetes).
interacts(tiotropium,ibandronate,asthma).
interacts(tiotropium,ibandronate,aseptic_necrosis_bone).
interacts(tiotropium,fluticasone,bronchial_spasm).
interacts(tiotropium,telmisartan,difficulty_breathing).
interacts(tiotropium,zoledronic_acid,asthma).
interacts(tiotropium,brinzolamide,asthma).
interacts(tiotropium,dofetilide,difficulty_breathing).
interacts(tiotropium,rosiglitazone,hyperglycaemia).
interacts(tiotropium,rosiglitazone,dysphonia).
interacts(tiotropium,lactulose,difficulty_breathing).
interacts(tiotropium,lactulose,dysphonia).
interacts(tiotropium,mometasone,asthma).
interacts(tiotropium,mometasone,chronic_obstructive_airway_disease).
interacts(tiotropium,mometasone,dysphonia).
interacts(tiotropium,gefitinib,cough).
interacts(tiotropium,desloratadine,cough).
interacts(tiotropium,desloratadine,difficulty_breathing).
interacts(tiotropium,desloratadine,neumonia).
interacts(tiotropium,olmesartan_medoxomil,asthma).
interacts(tiotropium,ezetimibe,muscle_spasm).
interacts(tiotropium,lenalidomide,thrombocytopenia).
interacts(tiotropium,rosuvastatin,muscle_spasm).
interacts(tiotropium,bimatoprost,cough).
interacts(tiotropium,bimatoprost,difficulty_breathing).
interacts(tiotropium,cisplatin,asthma).
interacts(tiotropium,cisplatin,difficulty_breathing).
interacts(tiotropium,iloprost,difficulty_breathing).
interacts(tiotropium,montelukast,asthma).
interacts(tiotropium,montelukast,cough).
interacts(tiotropium,montelukast,wheeze).
interacts(tiotropium,su11248,asthma).
interacts(tiotropium,su11248,cough).
interacts(tiotropium,su11248,difficulty_breathing).
interacts(tiotropium,sucralfate,asthma).
interacts(duloxetine,ibandronate,aseptic_necrosis_bone).
interacts(duloxetine,fluticasone,agitated).
interacts(duloxetine,fluticasone,insomnia).
interacts(duloxetine,darifenacin,tremor).
interacts(duloxetine,rosiglitazone,anorexia).
interacts(duloxetine,rosiglitazone,dyspepsia).
interacts(duloxetine,rosiglitazone,nausea).
interacts(duloxetine,rosiglitazone,loss_of_weight).
interacts(duloxetine,rosiglitazone,feeling_unwell).
interacts(duloxetine,allopurinol,high_blood_pressure).
interacts(duloxetine,allopurinol,arterial_pressure_nos_decreased).
interacts(duloxetine,allopurinol,heart_attack).
interacts(duloxetine,lactulose,agitated).
interacts(duloxetine,9-hydroxyrisperidone,diabetes).
interacts(duloxetine,9-hydroxyrisperidone,insomnia).
interacts(duloxetine,valdecoxib,transient_ischaemic_attack).
interacts(duloxetine,mometasone,anxiety).
interacts(duloxetine,mometasone,drowsiness).
interacts(duloxetine,mometasone,weight_gain).
interacts(duloxetine,desloratadine,insomnia).
interacts(duloxetine,pregabalin,attempted_suicide).
interacts(duloxetine,olmesartan_medoxomil,diabetes).
interacts(duloxetine,olmesartan_medoxomil,dizziness).
interacts(duloxetine,olmesartan_medoxomil,weight_gain).
interacts(duloxetine,ezetimibe,muscle_spasm).
interacts(duloxetine,ezetimibe,abnormal_gait).
interacts(duloxetine,nystatin,dizziness).
interacts(duloxetine,nystatin,hypoventilation).
interacts(duloxetine,montelukast,dysphonia).
interacts(duloxetine,tegaserod,diabetes).
interacts(duloxetine,tegaserod,drowsiness).
interacts(ibandronate,rosiglitazone,nausea).
interacts(ibandronate,mometasone,aseptic_necrosis_bone).
interacts(ibandronate,ezetimibe,aseptic_necrosis_bone).
interacts(ibandronate,montelukast,asthma).
interacts(olopatadine,fluticasone,asthma).
interacts(olopatadine,fluticasone,difficulty_breathing).
interacts(olopatadine,fluticasone,wheeze).
interacts(olopatadine,fluticasone,dysphonia).
interacts(olopatadine,mometasone,cough).
interacts(olopatadine,desloratadine,asthma).
interacts(olopatadine,desloratadine,difficulty_breathing).
interacts(olopatadine,ezetimibe,chest_pain).
interacts(olopatadine,ezetimibe,heart_attack).
interacts(olopatadine,ezetimibe,extremity_pain).
interacts(olopatadine,montelukast,cough).
interacts(olopatadine,montelukast,difficulty_breathing).
interacts(olopatadine,montelukast,dysphonia).
interacts(ftc,tenofovir_disoproxil_fumarate,acidosis).
interacts(fluticasone,rosiglitazone,asthma).
interacts(fluticasone,rosiglitazone,hyperglycaemia).
interacts(fluticasone,rosiglitazone,hypoglycaemia).
interacts(fluticasone,rosiglitazone,loss_of_weight).
interacts(fluticasone,lactulose,asthma).
interacts(fluticasone,lactulose,cough).
interacts(fluticasone,lactulose,wheeze).
interacts(fluticasone,lactulose,dysphonia).
interacts(fluticasone,moexipril,cough).
interacts(fluticasone,bosentan,cough).
interacts(fluticasone,bosentan,difficulty_breathing).
interacts(fluticasone,bosentan,wheeze).
interacts(fluticasone,bosentan,pain_in_throat).
interacts(fluticasone,bosentan,blindness).
interacts(fluticasone,tadalafil,asthma).
interacts(fluticasone,valdecoxib,difficulty_breathing).
interacts(fluticasone,valdecoxib,cardiac_decompensation).
interacts(fluticasone,valdecoxib,phlebothrombosis).
interacts(fluticasone,mometasone,difficulty_breathing).
interacts(fluticasone,gefitinib,difficulty_breathing).
interacts(fluticasone,desloratadine,bronchitis).
interacts(fluticasone,desloratadine,cough).
interacts(fluticasone,desloratadine,difficulty_breathing).
interacts(fluticasone,desloratadine,chronic_obstructive_airway_disease).
interacts(fluticasone,desloratadine,dysphonia).
interacts(fluticasone,pregabalin,asthma).
interacts(fluticasone,pregabalin,difficulty_breathing).
interacts(fluticasone,ezetimibe,asthma).
interacts(fluticasone,dutasteride,asthma).
interacts(fluticasone,varenicline,pain_in_throat).
interacts(fluticasone,varenicline,dysphonia).
interacts(fluticasone,lenalidomide,asthma).
interacts(fluticasone,lenalidomide,cough).
interacts(fluticasone,nateglinide,difficulty_breathing).
interacts(fluticasone,telithromycin,asthma).
interacts(fluticasone,telithromycin,muscle_spasm).
interacts(fluticasone,rosuvastatin,apoplexy).
interacts(fluticasone,rosuvastatin,dysphonia).
interacts(fluticasone,travoprost,cough).
interacts(fluticasone,bimatoprost,difficulty_breathing).
interacts(fluticasone,iloprost,asthma).
interacts(fluticasone,montelukast,bronchial_spasm).
interacts(fluticasone,montelukast,candida_infection).
interacts(fluticasone,montelukast,chest_pain).
interacts(fluticasone,montelukast,cough).
interacts(fluticasone,montelukast,difficulty_breathing).
interacts(fluticasone,montelukast,chronic_obstructive_airway_disease).
interacts(fluticasone,montelukast,neumonia).
interacts(fluticasone,montelukast,pain_in_throat).
interacts(fluticasone,montelukast,dysphonia).
interacts(fluticasone,sucralfate,cough).
interacts(fluticasone,cefdinir,wheeze).
interacts(fluticasone,pimecrolimus,asthma).
interacts(valganciclovir,nystatin,thrombotic_microangiopathy).
interacts(tipranavir,tenofovir_disoproxil_fumarate,elevated_triglycerides).
interacts(telmisartan,rosiglitazone,ecchymoses).
interacts(telmisartan,allopurinol,cardiac_decompensation).
interacts(telmisartan,montelukast,asthma).
interacts(zoledronic_acid,rosiglitazone,nausea).
interacts(zoledronic_acid,dutasteride,thrombocytopenia).
interacts(zoledronic_acid,sorafenib,thrombocytopenia).
interacts(zoledronic_acid,lenalidomide,body_temperature_increased).
interacts(zoledronic_acid,cisplatin,neutropenia).
interacts(zoledronic_acid,su11248,body_temperature_increased).
interacts(zoledronic_acid,su11248,leucopenia).
interacts(brinzolamide,bimatoprost,conjunctivitis).
interacts(brinzolamide,bimatoprost,glaucoma).
interacts(dofetilide,allopurinol,cardiac_decompensation).
interacts(dofetilide,rosuvastatin,heart_attack).
interacts(voriconazole,allopurinol,excess_potassium).
interacts(voriconazole,allopurinol,kidney_failure).
interacts(voriconazole,caspofungin,candida_infection).
interacts(voriconazole,caspofungin,bilirubinaemia).
interacts(voriconazole,caspofungin,hypokalaemia).
interacts(darifenacin,solifenacin_succinate,incontinence).
interacts(bleomycin,cisplatin,acute_myeloblastic_leukemia).
interacts(bleomycin,cisplatin,neutropenia).
interacts(rosiglitazone,allopurinol,anorexia).
interacts(rosiglitazone,allopurinol,dizziness).
interacts(rosiglitazone,allopurinol,hyperglycaemia).
interacts(rosiglitazone,allopurinol,kidney_failure).
interacts(rosiglitazone,lactulose,hyperglycaemia).
interacts(rosiglitazone,lactulose,hypoglycaemia).
interacts(rosiglitazone,moexipril,hyperglycaemia).
interacts(rosiglitazone,moexipril,hypoglycaemia).
interacts(rosiglitazone,vardenafil,hyperglycaemia).
interacts(rosiglitazone,vardenafil,hypoglycaemia).
interacts(rosiglitazone,tadalafil,hyperglycaemia).
interacts(rosiglitazone,tadalafil,hypoglycaemia).
interacts(rosiglitazone,valdecoxib,dyspepsia).
interacts(rosiglitazone,valdecoxib,loss_of_weight).
interacts(rosiglitazone,mometasone,anorexia).
interacts(rosiglitazone,mometasone,hyperglycaemia).
interacts(rosiglitazone,mometasone,hypoglycaemia).
interacts(rosiglitazone,mometasone,loss_of_weight).
interacts(rosiglitazone,desloratadine,diarrhea).
interacts(rosiglitazone,desloratadine,dyspepsia).
interacts(rosiglitazone,pregabalin,hyperglycaemia).
interacts(rosiglitazone,pregabalin,hypoglycaemia).
interacts(rosiglitazone,pregabalin,loss_of_weight).
interacts(rosiglitazone,olmesartan_medoxomil,anorexia).
interacts(rosiglitazone,olmesartan_medoxomil,ecchymoses).
interacts(rosiglitazone,olmesartan_medoxomil,nausea).
interacts(rosiglitazone,ezetimibe,anorexia).
interacts(rosiglitazone,ezetimibe,hypoglycaemia).
interacts(rosiglitazone,ezetimibe,nausea).
interacts(rosiglitazone,ezetimibe,loss_of_weight).
interacts(rosiglitazone,dutasteride,hypoglycaemia).
interacts(rosiglitazone,dutasteride,loss_of_weight).
interacts(rosiglitazone,colesevelam_hydrochloride,hyperglycaemia).
interacts(rosiglitazone,varenicline,hypoglycaemia).
interacts(rosiglitazone,varenicline,loss_of_weight).
interacts(rosiglitazone,nateglinide,hypoglycaemia).
interacts(rosiglitazone,sevelamer,nausea).
interacts(rosiglitazone,nystatin,hyperglycaemia).
interacts(rosiglitazone,nystatin,loss_of_weight).
interacts(rosiglitazone,rosuvastatin,anorexia).
interacts(rosiglitazone,rosuvastatin,hyperglycaemia).
interacts(rosiglitazone,rosuvastatin,hypoglycaemia).
interacts(rosiglitazone,rosuvastatin,loss_of_weight).
interacts(rosiglitazone,bimatoprost,hyperglycaemia).
interacts(rosiglitazone,bimatoprost,emesis).
interacts(rosiglitazone,bimatoprost,loss_of_weight).
interacts(rosiglitazone,montelukast,anorexia).
interacts(rosiglitazone,montelukast,asthma).
interacts(rosiglitazone,montelukast,hypoglycaemia).
interacts(rosiglitazone,montelukast,loss_of_weight).
interacts(rosiglitazone,sulfasalazine,nausea).
interacts(rosiglitazone,sulfasalazine,loss_of_weight).
interacts(rosiglitazone,tegaserod,hypoglycaemia).
interacts(rosiglitazone,sucralfate,hypoglycaemia).
interacts(rosiglitazone,sucralfate,loss_of_weight).
interacts(allopurinol,lactulose,afib).
interacts(allopurinol,lactulose,arterial_pressure_nos_decreased).
interacts(allopurinol,lactulose,apoplexy).
interacts(allopurinol,bosentan,arterial_pressure_nos_decreased).
interacts(allopurinol,vardenafil,heart_attack).
interacts(allopurinol,valdecoxib,acid_reflux).
interacts(allopurinol,valdecoxib,cardiac_decompensation).
interacts(allopurinol,valdecoxib,hyperlipaemia).
interacts(allopurinol,valdecoxib,heart_attack).
interacts(allopurinol,valdecoxib,apoplexy).
interacts(allopurinol,gefitinib,neumonia).
interacts(allopurinol,pregabalin,arterial_pressure_nos_decreased).
interacts(allopurinol,olmesartan_medoxomil,cardiac_decompensation).
interacts(allopurinol,olmesartan_medoxomil,kidney_failure).
interacts(allopurinol,olmesartan_medoxomil,apoplexy).
interacts(allopurinol,posaconazole,arterial_pressure_nos_decreased).
interacts(allopurinol,posaconazole,acute_kidney_failure).
interacts(allopurinol,ezetimibe,cardiac_decompensation).
interacts(allopurinol,ezetimibe,heart_attack).
interacts(allopurinol,ezetimibe,muscle_spasm).
interacts(allopurinol,lenalidomide,cardiac_decompensation).
interacts(allopurinol,lenalidomide,chronic_obstructive_airway_disease).
interacts(allopurinol,nateglinide,cardiac_failure).
interacts(allopurinol,mercaptopurine,heart_attack).
interacts(allopurinol,dasatinib,acute_kidney_failure).
interacts(allopurinol,rosuvastatin,heart_attack).
interacts(allopurinol,cisplatin,blood_sodium_decreased).
interacts(allopurinol,cisplatin,acute_kidney_failure).
interacts(allopurinol,montelukast,cardiac_decompensation).
interacts(allopurinol,su11248,bradycardia).
interacts(allopurinol,tegaserod,apoplexy).
interacts(allopurinol,sucralfate,bradycardia).
interacts(lactulose,bortezomib,aseptic_necrosis_bone).
interacts(lactulose,valdecoxib,high_blood_pressure).
interacts(lactulose,valdecoxib,heart_attack).
interacts(lactulose,valdecoxib,apoplexy).
interacts(lactulose,mometasone,difficulty_breathing).
interacts(lactulose,pregabalin,heart_attack).
interacts(lactulose,aprepitant,dehydration).
interacts(lactulose,aprepitant,neumonia).
interacts(lactulose,lenalidomide,infection).
interacts(lactulose,neomycin,emesis).
interacts(lactulose,nystatin,candida_infection).
interacts(lactulose,nystatin,neumonia).
interacts(lactulose,nystatin,emesis).
interacts(lactulose,rosuvastatin,apoplexy).
interacts(lactulose,cisplatin,body_temperature_increased).
interacts(lactulose,cisplatin,bone_marrow_failure).
interacts(lactulose,su11248,diarrhea).
interacts(lactulose,sucralfate,abdominal_distension).
interacts(lactulose,sucralfate,chest_pain).
interacts(bortezomib,cisplatin,neutropenia).
interacts(bosentan,montelukast,cough).
interacts(bosentan,montelukast,dysphonia).
interacts(vardenafil,tadalafil,scotoma).
interacts(vardenafil,tadalafil,blindness).
interacts(vardenafil,rosuvastatin,heart_attack).
interacts(tadalafil,valdecoxib,arteriosclerotic_heart_disease).
interacts(valdecoxib,mometasone,transient_ischaemic_attack).
interacts(valdecoxib,mometasone,cardiac_disease).
interacts(valdecoxib,mometasone,heart_attack).
interacts(valdecoxib,mometasone,apoplexy).
interacts(valdecoxib,desloratadine,chest_pain).
interacts(valdecoxib,desloratadine,cardiac_disease).
interacts(valdecoxib,desloratadine,hypoventilation).
interacts(valdecoxib,olmesartan_medoxomil,cardiac_disease).
interacts(valdecoxib,olmesartan_medoxomil,apoplexy).
interacts(valdecoxib,ezetimibe,cardiac_disease).
interacts(valdecoxib,rosuvastatin,chest_pain).
interacts(valdecoxib,rosuvastatin,cardiac_disease).
interacts(valdecoxib,montelukast,high_blood_pressure).
interacts(valdecoxib,montelukast,heart_attack).
interacts(valdecoxib,montelukast,apoplexy).
interacts(valdecoxib,sucralfate,heart_attack).
interacts(valdecoxib,sucralfate,extremity_pain).
interacts(valdecoxib,sucralfate,apoplexy).
interacts(mometasone,desloratadine,asthma).
interacts(mometasone,desloratadine,difficulty_breathing).
interacts(mometasone,desloratadine,wheeze).
interacts(mometasone,ezetimibe,difficulty_breathing).
interacts(mometasone,ezetimibe,extremity_pain).
interacts(mometasone,dutasteride,asthma).
interacts(mometasone,varenicline,diabetes).
interacts(mometasone,telithromycin,difficulty_breathing).
interacts(mometasone,telithromycin,dysphonia).
interacts(mometasone,rosuvastatin,elevated_cholesterol).
interacts(mometasone,rosuvastatin,heart_attack).
interacts(mometasone,montelukast,difficulty_breathing).
interacts(mometasone,montelukast,dysphonia).
interacts(mometasone,tegaserod,asthma).
interacts(gefitinib,nystatin,dehydration).
interacts(gefitinib,cisplatin,dehydration).
interacts(gefitinib,cisplatin,pleural_effusion).
interacts(gefitinib,cisplatin,thrombocytopenia).
interacts(desloratadine,rosuvastatin,heart_attack).
interacts(desloratadine,montelukast,bronchial_spasm).
interacts(desloratadine,montelukast,cough).
interacts(desloratadine,montelukast,difficulty_breathing).
interacts(desloratadine,montelukast,dysphonia).
interacts(pregabalin,ezetimibe,aching_muscles).
interacts(pregabalin,lenalidomide,neutropenia).
interacts(pregabalin,lenalidomide,aseptic_necrosis_bone).
interacts(pregabalin,nystatin,insomnia).
interacts(pregabalin,montelukast,difficulty_breathing).
interacts(olmesartan_medoxomil,colesevelam_hydrochloride,arterial_pressure_nos_increased).
interacts(olmesartan_medoxomil,sucralfate,arterial_pressure_nos_increased).
interacts(nitric_oxide,nystatin,sepsis).
interacts(posaconazole,caspofungin,septic_shock).
interacts(palonosetron,cisplatin,body_temperature_increased).
interacts(palonosetron,cisplatin,neutropenia).
interacts(ezetimibe,dutasteride,muscle_spasm).
interacts(ezetimibe,lenalidomide,aseptic_necrosis_bone).
interacts(ezetimibe,montelukast,heart_attack).
interacts(ezetimibe,tegaserod,muscle_weakness).
interacts(ezetimibe,aliskiren,high_blood_pressure).
interacts(aprepitant,cisplatin,body_temperature_increased).
interacts(aprepitant,cisplatin,thrombocytopenia).
interacts(solifenacin_succinate,montelukast,asthma).
interacts(cinacalcet,lambda,blood_calcium_increased).
interacts(cinacalcet,lambda,peritonitis).
interacts(cinacalcet,sevelamer,asystole).
interacts(cinacalcet,sevelamer,peritonitis).
interacts(cinacalcet,paricalcitol,bone_marrow_failure).
interacts(colesevelam_hydrochloride,montelukast,asthma).
interacts(varenicline,rosuvastatin,muscle_spasm).
interacts(varenicline,montelukast,asthma).
interacts(varenicline,montelukast,difficulty_breathing).
interacts(lambda,sevelamer,asystole).
interacts(lambda,paricalcitol,chronic_kidney_disease).
interacts(ciclesonide,montelukast,difficulty_breathing).
interacts(telithromycin,montelukast,asthma).
interacts(telithromycin,montelukast,bronchitis).
interacts(telithromycin,montelukast,difficulty_breathing).
interacts(sevelamer,paricalcitol,chronic_kidney_disease).
interacts(sevelamer,paricalcitol,aplasia_pure_red_cell).
interacts(nystatin,cisplatin,body_temperature_increased).
interacts(nystatin,cisplatin,thrombocytopenia).
interacts(nystatin,montelukast,cough).
interacts(nystatin,montelukast,difficulty_breathing).
interacts(nystatin,montelukast,chronic_obstructive_airway_disease).
interacts(nystatin,montelukast,dysphonia).
interacts(dacarbazine,cisplatin,neutropenia).
interacts(dacarbazine,cisplatin,neumonia).
interacts(dacarbazine,cisplatin,thrombocytopenia).
interacts(bimatoprost,montelukast,asthma).
interacts(bimatoprost,montelukast,neumonia).
interacts(iloprost,montelukast,difficulty_breathing).
interacts(montelukast,tegaserod,asthma).
interacts(montelukast,sucralfate,asthma).
interacts(montelukast,sucralfate,pleural_pain).
interacts(montelukast,sucralfate,chronic_obstructive_airway_disease).
interacts(montelukast,cefdinir,asthma).
interacts(su11248,sucralfate,abdominal_pain).
